name: Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Compose services
      - name: Build Docker Compose services
        run: docker compose up --build -d

      # Step 4: Test the services
      # You can replace this with custom tests, depending on what your containers do.
      - name: Run basic test (Check if services are running)
        run: docker compose ps

      # Step 5: Stop and clean up Docker Compose services
      - name: Stop Docker Compose
        run: docker compose down