name: Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-test-raspi-build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose services
        run: docker compose up --build -d

      - name: Run basic test (Check if services are running)
        run: docker compose ps
        
      - name: Stop Docker Compose
        run: docker compose down

  docker-compose-test-mac-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose services
        run: docker compose up --build -d

      - name: Run basic test (Check if services are running)
        run: docker compose ps

      - name: Stop Docker Compose
        run: docker compose down