name: Makefile CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)