name: Makefile CI

on: push
  #   branches: [ $default-branch ]
  #   paths:
  #     - 'demo-project/**'   # Listen for changes in the 'src' directory
  # pull_request:
  #   branches: [ $default-branch ]
  #   paths:
  #     - 'demo-project/**'   # Also listen for pull requests that change files in the 'src' directory
jobs:
  build:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v4
      - name: Check Files in the directory
        run: ls -la
      - name: Build the Docker image
        run: sudo DOCKER_BUILDKIT=1 docker build --no-cache -t rpi-temperature -f Dockerfile .
        working-directory: ./demo-project 