name: Makefile CI

on:
  push:
    branches: [ $default-branch ]
    paths:
      - 'demo-project/**'   # Listen for changes in the 'src' directory
  pull_request:
    branches: [ $default-branch ]
    paths:
      - 'demo-project/**'   # Also listen for pull requests that change files in the 'src' directory

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)